# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Tournament.create(name: 'Albury/Wodonga')
Tournament.create(name: 'ANZAC Open')
Tournament.create(name: 'Australian Open Singles')
Tournament.create(name: 'Berri Resort Hotel Open')
Tournament.create(name: 'Big Guns')
Tournament.create(name: 'Darwin Open')
Tournament.create(name: 'Empire Classic')
Tournament.create(name: 'Geelong Open')
Tournament.create(name: 'Killer Crossover')
Tournament.create(name: 'LPCues')
Tournament.create(name: 'Western National')

Player.create(first_name: 'Aaron', last_name: 'Mahoney')
Player.create(first_name: 'Aaron', last_name: 'Tretheway')
Player.create(first_name: 'Adam', last_name: 'Andretzke')
Player.create(first_name: 'Adam', last_name: 'Bleumink')
Player.create(first_name: 'Adrian', last_name: 'Lancaster')
Player.create(first_name: 'Alan', last_name: 'Brown')
Player.create(first_name: 'Alec', last_name: 'Evreniadis')
Player.create(first_name: 'Alex', last_name: 'Pace')
Player.create(first_name: 'Alex', last_name: 'Wadell')
Player.create(first_name: 'Alf', last_name: 'Grasson')
Player.create(first_name: 'Andrew', last_name: 'Chaplin')
Player.create(first_name: 'Andy', last_name: 'Barnett')
Player.create(first_name: 'Andy', last_name: 'Ripley')
Player.create(first_name: 'Anthony', last_name: 'Grantham')
Player.create(first_name: 'Ayden', last_name: 'Hodgson')
Player.create(first_name: 'Barry', last_name: 'King')
Player.create(first_name: 'Barry', last_name: 'Kitchener Jnr')
Player.create(first_name: 'Barry', last_name: 'Wakefield')
Player.create(first_name: 'Bayden', last_name: 'Jackson (NZ)')
Player.create(first_name: 'Bella', last_name: 'Di Giorgio')
Player.create(first_name: 'Ben', last_name: 'Crawley')
Player.create(first_name: 'Ben', last_name: 'Foster')
Player.create(first_name: 'Ben', last_name: 'Judge')
Player.create(first_name: 'Ben', last_name: 'Nunan')
Player.create(first_name: 'Ben', last_name: 'Pottinger')
Player.create(first_name: 'Blair', last_name: 'Kirkcaldy')
Player.create(first_name: 'Bobby', last_name: 'Dennis')
Player.create(first_name: 'Boris', last_name: 'Krasic')
Player.create(first_name: 'Brad', last_name: 'Redman')
Player.create(first_name: 'Brad', last_name: 'Richmond')
Player.create(first_name: 'Bradd', last_name: 'Hill')
Player.create(first_name: 'Brent', last_name: 'Hampton')
Player.create(first_name: 'Brent', last_name: 'Read')
Player.create(first_name: 'Brenton', last_name: 'Collier')
Player.create(first_name: 'Brett', last_name: 'Rogers')
Player.create(first_name: 'Brian', last_name: 'Daly')
Player.create(first_name: 'Broe', last_name: 'Shiells')
Player.create(first_name: 'Bronson', last_name: 'Blackmore')
Player.create(first_name: 'Cale', last_name: 'Barrett')
Player.create(first_name: 'Callum', last_name: 'Saunders')
Player.create(first_name: 'Calvin', last_name: 'Chong')
Player.create(first_name: 'Cameron', last_name: 'Barrett-Brook')
Player.create(first_name: 'Cameron', last_name: 'Carey')
Player.create(first_name: 'Carl', last_name: 'Borsi')
Player.create(first_name: 'Chase', last_name: 'Daley')
Player.create(first_name: 'Choco', last_name: 'Khan')
Player.create(first_name: 'Chris', last_name: 'Beagley')
Player.create(first_name: 'Chris', last_name: 'Buck')
Player.create(first_name: 'Chris', last_name: 'Jeffery')
Player.create(first_name: 'Chris', last_name: 'Lilly')
Player.create(first_name: 'Chris', last_name: 'McKenna')
Player.create(first_name: 'Cindy', last_name: 'Blackmore')
Player.create(first_name: 'Clem', last_name: 'Chan')
Player.create(first_name: 'Clint', last_name: 'Kappler')
Player.create(first_name: 'Colin', last_name: 'Hood')
Player.create(first_name: 'Craig', last_name: 'Riley')
Player.create(first_name: 'Craig', last_name: 'Stevens')
Player.create(first_name: 'Cranne', last_name: 'Wrigley')
Player.create(first_name: 'Cristina', last_name: 'Sarmento')
Player.create(first_name: 'Dale', last_name: 'Bolton')
Player.create(first_name: 'Dale', last_name: 'Kent')
Player.create(first_name: 'Dale', last_name: 'Watson')
Player.create(first_name: 'Damian', last_name: 'Walsh')
Player.create(first_name: 'Dan', last_name: 'Henwood')
Player.create(first_name: 'Dan', last_name: 'Leck')
Player.create(first_name: 'Dan', last_name: 'Lynch')
Player.create(first_name: 'Dane', last_name: 'Beeton')
Player.create(first_name: 'Dane', last_name: 'Taylor')
Player.create(first_name: 'Daniel', last_name: 'Bale')
Player.create(first_name: 'Daniel', last_name: 'Banfield')
Player.create(first_name: 'Daniel', last_name: 'Clark')
Player.create(first_name: 'Daniel', last_name: 'Greatz')
Player.create(first_name: 'Daniel', last_name: 'Steller')
Player.create(first_name: 'Daniel', last_name: 'Thorp')
Player.create(first_name: 'Daniel', last_name: 'Warne')
Player.create(first_name: 'Danny', last_name: 'Bowen (NZ)')
Player.create(first_name: 'Danyal', last_name: 'Porter')
Player.create(first_name: 'Darren', last_name: 'Gordon')
Player.create(first_name: 'Darren', last_name: 'Morris')
Player.create(first_name: 'Darren', last_name: 'Shaw')
Player.create(first_name: 'Darren', last_name: 'Waite')
Player.create(first_name: 'Dave', last_name: 'Krasic')
Player.create(first_name: 'Dave', last_name: 'Limareff')
Player.create(first_name: 'Dave', last_name: 'Rothall')
Player.create(first_name: 'Dave', last_name: 'Ryan')
Player.create(first_name: 'David', last_name: 'Armstrong')
Player.create(first_name: 'David', last_name: 'Cooper')
Player.create(first_name: 'David', last_name: 'Ewing')
Player.create(first_name: 'David', last_name: 'Fallon')
Player.create(first_name: 'David', last_name: 'Pilgrim')
Player.create(first_name: 'Dax', last_name: 'Wasley')
Player.create(first_name: 'Dayne', last_name: 'Van Kempem')
Player.create(first_name: 'Dean', last_name: 'Welsh')
Player.create(first_name: 'Dene', last_name: 'Hereamia')
Player.create(first_name: 'Denis', last_name: 'Hynes')
Player.create(first_name: 'Don', last_name: 'Colbert')
Player.create(first_name: 'Drew', last_name: 'Tatt')
Player.create(first_name: 'Eddie', last_name: 'McCaughey')
Player.create(first_name: 'Edward', last_name: 'Cyganov')
Player.create(first_name: 'Ekky', last_name: 'Lakthong')
Player.create(first_name: 'Elise', last_name: 'Mabbott')
Player.create(first_name: 'Enrico', last_name: 'Di Giorgio')
Player.create(first_name: 'Filip', last_name: 'Misic')
Player.create(first_name: 'Gary', last_name: 'Wilcox')
Player.create(first_name: 'Gavin', last_name: 'Furlong')
Player.create(first_name: 'Gavin', last_name: 'Roberts')
Player.create(first_name: 'George', last_name: 'Ninte')
Player.create(first_name: 'Glen', last_name: 'Bednarczyk')
Player.create(first_name: 'Glen', last_name: 'Ferris')
Player.create(first_name: 'Gordan', last_name: 'Whittaker')
Player.create(first_name: 'Grant', last_name: 'Weekley')
Player.create(first_name: 'Greg', last_name: 'Wells')
Player.create(first_name: 'Gus', last_name: 'Di Giorgio')
Player.create(first_name: 'Gwen', last_name: 'Anderson')
Player.create(first_name: 'Ian', last_name: 'Hinton')
Player.create(first_name: 'Ian', last_name: 'Will')
Player.create(first_name: 'Ivan', last_name: 'Jovanovic')
Player.create(first_name: 'JJ', last_name: 'Spink')
Player.create(first_name: 'Jack', last_name: 'Hunter')
Player.create(first_name: 'Jack', last_name: 'Kiang')
Player.create(first_name: 'Jack', last_name: 'Lewis')
Player.create(first_name: 'Jackson', last_name: 'Nguyen')
Player.create(first_name: 'Jacob', last_name: 'Sumner')
Player.create(first_name: 'Jake', last_name: 'McCartney')
Player.create(first_name: 'Jakk', last_name: 'Phillips')
Player.create(first_name: 'James', last_name: 'Delahunty')
Player.create(first_name: 'James', last_name: 'Dillon')
Player.create(first_name: 'James', last_name: 'Georgiadis')
Player.create(first_name: 'James', last_name: 'Meckiff')
Player.create(first_name: 'James', last_name: 'Mifsud')
Player.create(first_name: 'James', last_name: 'Rocky Hammond')
Player.create(first_name: 'Jamie', last_name: 'Buettner')
Player.create(first_name: 'Jamie', last_name: 'Stevens')
Player.create(first_name: 'Jarrad', last_name: 'Page')
Player.create(first_name: 'Jasely', last_name: 'Dimer')
Player.create(first_name: 'Jason', last_name: 'Boyd')
Player.create(first_name: 'Jason', last_name: 'Casey')
Player.create(first_name: 'Jason', last_name: 'Foster')
Player.create(first_name: 'Jason', last_name: 'Hawker')
Player.create(first_name: 'Jason', last_name: 'Kyranis')
Player.create(first_name: 'Jason', last_name: 'Tanaskovic')
Player.create(first_name: 'Jason', last_name: 'Tucker')
Player.create(first_name: 'Jayden', last_name: 'Domeika')
Player.create(first_name: 'Jayson', last_name: 'Kelly')
Player.create(first_name: 'Jeremy', last_name: 'Bower')
Player.create(first_name: 'Jeremy', last_name: 'McGuire')
Player.create(first_name: 'Jesse', last_name: 'Browne')
Player.create(first_name: 'Jim', last_name: 'Rene')
Player.create(first_name: 'Jimi', last_name: 'Serci')
Player.create(first_name: 'Jock', last_name: 'Pittman')
Player.create(first_name: 'Johl', last_name: 'Younger')
Player.create(first_name: 'John', last_name: 'Barclay')
Player.create(first_name: 'John', last_name: 'Barton')
Player.create(first_name: 'John', last_name: 'Hilton')
Player.create(first_name: 'John', last_name: 'McLaren')
Player.create(first_name: 'John', last_name: 'Monaghan')
Player.create(first_name: 'John', last_name: 'Pagden')
Player.create(first_name: 'John', last_name: 'Raczkowski')
Player.create(first_name: 'John', last_name: 'Russell')
Player.create(first_name: 'Jordan', last_name: 'Matara')
Player.create(first_name: 'Josh', last_name: 'Boyle')
Player.create(first_name: 'Josh', last_name: 'Gorski')
Player.create(first_name: 'Josh', last_name: 'Ireland')
Player.create(first_name: 'Josh', last_name: 'Mills')
Player.create(first_name: 'Joshua', last_name: 'Sapeer')
Player.create(first_name: 'Joy', last_name: 'Sullivan')
Player.create(first_name: 'Juan-Pierre', last_name: 'Moneron')
Player.create(first_name: 'Judty', last_name: 'Bradshaw')
Player.create(first_name: 'Juke', last_name: 'Anglesey')
Player.create(first_name: 'Justin', last_name: 'Campbell')
Player.create(first_name: 'Justin', last_name: 'Kennedy')
Player.create(first_name: 'Justin', last_name: 'Sajich')
Player.create(first_name: 'Justin', last_name: 'Thursby')
Player.create(first_name: 'Justin', last_name: 'Van Diepen')
Player.create(first_name: 'Keegan', last_name: 'Reid')
Player.create(first_name: 'Keenan', last_name: 'Cigler')
Player.create(first_name: 'Kelvin', last_name: 'Lee')
Player.create(first_name: 'Kenny', last_name: 'Nicol')
Player.create(first_name: 'Kevin', last_name: 'Malek')
Player.create(first_name: 'Kim', last_name: 'Bucholz')
Player.create(first_name: 'Kolbe', last_name: 'Poole')
Player.create(first_name: 'Kurt', last_name: 'Dunham')
Player.create(first_name: 'Kym', last_name: 'Saunders')
Player.create(first_name: 'Kyriakos', last_name: 'Michaelides (NZ)')
Player.create(first_name: 'Laurie', last_name: 'Mahony')
Player.create(first_name: 'Lee', last_name: 'Thayre')
Player.create(first_name: 'Leigh', last_name: 'Gilpin')
Player.create(first_name: 'Leisa', last_name: 'Sjaardema')
Player.create(first_name: 'Lisa', last_name: 'Garvey')
Player.create(first_name: 'Lui', last_name: 'Iarossi')
Player.create(first_name: 'Luke', last_name: 'Anglesey')
Player.create(first_name: 'Luke', last_name: 'Foster')
Player.create(first_name: 'Luke', last_name: 'Smartt')
Player.create(first_name: 'Macwin', last_name: 'Fernandes')
Player.create(first_name: 'Mandar', last_name: 'Ranganeker')
Player.create(first_name: 'Marc', last_name: 'Robertson')
Player.create(first_name: 'Marcus', last_name: 'Harrison')
Player.create(first_name: 'Marg', last_name: 'Gorski')
Player.create(first_name: 'Mark', last_name: 'Bradley')
Player.create(first_name: 'Mark', last_name: 'Carroll')
Player.create(first_name: 'Mark', last_name: 'Curwood')
Player.create(first_name: 'Mark', last_name: 'Gottlieb')
Player.create(first_name: 'Mark', last_name: 'Stone')
Player.create(first_name: 'Mark', last_name: 'Warry')
Player.create(first_name: 'Mark', last_name: 'Wood')
Player.create(first_name: 'Martin', last_name: 'McCabe')
Player.create(first_name: 'Martin', last_name: 'Nicol')
Player.create(first_name: 'Marty', last_name: 'Jelenik')
Player.create(first_name: 'Matt', last_name: 'Curwood')
Player.create(first_name: 'Matt', last_name: 'Harmon')
Player.create(first_name: 'Matt', last_name: 'McInnes (NZ)')
Player.create(first_name: 'Matthew', last_name: 'Bolton')
Player.create(first_name: 'Matthew', last_name: 'Wicks')
Player.create(first_name: 'Matty', last_name: 'Diatschenko')
Player.create(first_name: 'Melanie', last_name: 'Sanders')
Player.create(first_name: 'Michael', last_name: 'Ballam')
Player.create(first_name: 'Michael', last_name: 'Cacciola')
Player.create(first_name: 'Michael', last_name: 'Cloney')
Player.create(first_name: 'Michael', last_name: 'Fayad')
Player.create(first_name: 'Michael', last_name: 'Hayes')
Player.create(first_name: 'Michael', last_name: 'Masal')
Player.create(first_name: 'Michael', last_name: 'McCalden')
Player.create(first_name: 'Michael', last_name: 'Mihaljevic')
Player.create(first_name: 'Michael', last_name: 'Phillips')
Player.create(first_name: 'Michael', last_name: 'Reardon')
Player.create(first_name: 'Michael', last_name: 'Scerri')
Player.create(first_name: 'Mick', last_name: 'Delahunty')
Player.create(first_name: 'Mick', last_name: 'Hill (UK)')
Player.create(first_name: 'Mick', last_name: 'Norton')
Player.create(first_name: 'Mike', last_name: 'Ballam')
Player.create(first_name: 'Nathan', last_name: 'Harris')
Player.create(first_name: 'Nathan', last_name: 'McMahon')
Player.create(first_name: 'Nathan', last_name: 'Nemes')
Player.create(first_name: 'Nathan', last_name: 'Soder')
Player.create(first_name: 'Neil', last_name: 'Whitbread')
Player.create(first_name: 'Nelson', last_name: 'Chater')
Player.create(first_name: 'Neville', last_name: 'Lovis')
Player.create(first_name: 'Ngoc', last_name: 'Le')
Player.create(first_name: 'Nick', last_name: 'Hore')
Player.create(first_name: 'Nick', last_name: 'Howie')
Player.create(first_name: 'Nick', last_name: 'Palat')
Player.create(first_name: 'Nick', last_name: 'Young')
Player.create(first_name: 'Noel', last_name: 'Fontana')
Player.create(first_name: 'Patrick', last_name: 'Hood')
Player.create(first_name: 'Paul', last_name: 'Gibbons')
Player.create(first_name: 'Paul', last_name: 'Haebich')
Player.create(first_name: 'Paul', last_name: 'Hancock')
Player.create(first_name: 'Paul', last_name: 'Pike')
Player.create(first_name: 'Paull', last_name: 'Clack')
Player.create(first_name: 'Peter', last_name: 'Butterworth')
Player.create(first_name: 'Peter', last_name: 'Glidden')
Player.create(first_name: 'Peter', last_name: 'Rivett')
Player.create(first_name: 'Phil', last_name: 'Jones')
Player.create(first_name: 'Ralph', last_name: 'Tassone')
Player.create(first_name: 'Ratan', last_name: 'Banala')
Player.create(first_name: 'Reese', last_name: 'Young')
Player.create(first_name: 'Resham', last_name: 'Ramjali')
Player.create(first_name: 'Rhys', last_name: 'Godden ')
Player.create(first_name: 'Rick', last_name: 'Coleman')
Player.create(first_name: 'Ricky', last_name: 'Emery')
Player.create(first_name: 'Ricky', last_name: 'Perkins')
Player.create(first_name: 'Rob', last_name: 'Bowen')
Player.create(first_name: 'Robbie', last_name: 'Savage')
Player.create(first_name: 'Robert', last_name: 'Tiller')
Player.create(first_name: 'Rohnish', last_name: 'Soodun')
Player.create(first_name: 'Roland', last_name: 'Green')
Player.create(first_name: 'Ron', last_name: 'Callander')
Player.create(first_name: 'Ron', last_name: 'Kelly')
Player.create(first_name: 'Ronnie', last_name: 'George')
Player.create(first_name: 'Roy', last_name: 'Noblett')
Player.create(first_name: 'Roy', last_name: 'Tan')
Player.create(first_name: 'Rusty', last_name: 'Wheeler')
Player.create(first_name: 'Ryan', last_name: 'Craig')
Player.create(first_name: 'Ryan', last_name: 'Meuris')
Player.create(first_name: 'Ryan', last_name: 'Thomerson')
Player.create(first_name: 'Sahil', last_name: 'Sharma')
Player.create(first_name: 'Sam', last_name: 'Crunden-Peck')
Player.create(first_name: 'Sawan', last_name: 'Naker')
Player.create(first_name: 'Scott', last_name: 'Alexander')
Player.create(first_name: 'Scott', last_name: 'Healy')
Player.create(first_name: 'Scott', last_name: 'Matthews')
Player.create(first_name: 'Scott', last_name: 'McKay')
Player.create(first_name: 'Scott', last_name: 'Peel')
Player.create(first_name: 'Sean', last_name: 'Partridge')
Player.create(first_name: 'Shane', last_name: 'Alan')
Player.create(first_name: 'Shane', last_name: 'Charles')
Player.create(first_name: 'Shane', last_name: 'Cripps')
Player.create(first_name: 'Shane', last_name: 'Falconer')
Player.create(first_name: 'Shane', last_name: 'Fell')
Player.create(first_name: 'Shane', last_name: 'Irons')
Player.create(first_name: 'Shane', last_name: 'Lee')
Player.create(first_name: 'Shannon', last_name: 'Purcell')
Player.create(first_name: 'Shaun', last_name: 'Durbridge')
Player.create(first_name: 'Shawn', last_name: 'Budd')
Player.create(first_name: 'Shawn', last_name: 'Salmon')
Player.create(first_name: 'Simon', last_name: 'Galdes')
Player.create(first_name: 'Simon', last_name: 'Gray')
Player.create(first_name: 'Simon', last_name: 'Singleton (NZ)')
Player.create(first_name: 'Sonia', last_name: 'Ferguson')
Player.create(first_name: 'Sonny', last_name: 'Lister')
Player.create(first_name: 'Stan', last_name: 'Iakovakis')
Player.create(first_name: 'Steve', last_name: 'Brett')
Player.create(first_name: 'Steve', last_name: 'Dawe (UK)')
Player.create(first_name: 'Steve', last_name: 'Dempsey (Ire)')
Player.create(first_name: 'Steve', last_name: 'Denton')
Player.create(first_name: 'Steve', last_name: 'DuKamp')
Player.create(first_name: 'Steve', last_name: 'Gray')
Player.create(first_name: 'Steve', last_name: 'Hale')
Player.create(first_name: 'Steve', last_name: 'Halliday')
Player.create(first_name: 'Steve', last_name: 'Jamieson')
Player.create(first_name: 'Steve', last_name: 'Saxon')
Player.create(first_name: 'Steve', last_name: 'Thomas')
Player.create(first_name: 'Steve', last_name: 'Tran')
Player.create(first_name: 'Steve', last_name: 'Viney')
Player.create(first_name: 'Steve', last_name: 'Woods')
Player.create(first_name: 'Steven', last_name: 'Brown')
Player.create(first_name: 'Stone', last_name: 'Stenhouse')
Player.create(first_name: 'Stuart', last_name: 'Kingsbury')
Player.create(first_name: 'Suzanne', last_name: 'Bussanich')
Player.create(first_name: 'Temujin', last_name: 'Dixon')
Player.create(first_name: 'Terry', last_name: 'Shiels')
Player.create(first_name: 'Thomas', last_name: 'Warren')
Player.create(first_name: 'Tim', last_name: 'Hyde')
Player.create(first_name: 'Tim', last_name: 'Martlew')
Player.create(first_name: 'Tim', last_name: 'Olencewicz')
Player.create(first_name: 'Tolkym', last_name: 'Gava')
Player.create(first_name: 'Tom', last_name: 'Drewell')
Player.create(first_name: 'Tom', last_name: 'Hall Mcleod')
Player.create(first_name: 'Tom', last_name: 'Jelly')
Player.create(first_name: 'Tony', last_name: 'Jordans')
Player.create(first_name: 'Tony', last_name: 'Kostov')
Player.create(first_name: 'Tony', last_name: 'Wakefield')
Player.create(first_name: 'Travis', last_name: 'Crawley')
Player.create(first_name: 'Travis', last_name: 'Henderson')
Player.create(first_name: 'Travis', last_name: 'Martin')
Player.create(first_name: 'Tristan', last_name: 'Massang')
Player.create(first_name: 'Troy', last_name: 'Rudling')
Player.create(first_name: 'Tyron', last_name: 'King')
Player.create(first_name: 'Tyson', last_name: 'Howie')
Player.create(first_name: 'Vic', last_name: 'Opalicki')
Player.create(first_name: 'Vijay', last_name: 'Randall')
Player.create(first_name: 'Vince', last_name: 'Lawson')
Player.create(first_name: 'Wayne', last_name: 'Gilmour')
Player.create(first_name: 'Wayne', last_name: 'Richardson')
Player.create(first_name: 'Wayne', last_name: 'Stubbs')
Player.create(first_name: 'Wes', last_name: 'Coutts')
Player.create(first_name: 'Wes', last_name: 'Hayes')
Player.create(first_name: 'William', last_name: 'Kossack')
