class MergeDuplicatePlayerCandidates < ActiveRecord::Migration[7.2]
  class Player < ActiveRecord::Base
    has_many :placings

    def merge_into(other)
      placings.each do |placing|
        next if Placing.exists?(edition: placing.edition, player: other)
        placing.update!(player: other)
      end
      destroy
    end
  end
  class Placing < ActiveRecord::Base
    belongs_to :edition
    belongs_to :player
  end

  # Source: ~/Downloads/duplicate_player_candidates.xlsx ("Duplicate Candidates" sheet).
  # 99 name-similarity groups (4 Very likely, 86 Likely, 9 Worth a look) generated by
  # text-matching only -- not verified against tournament history, DOB, or club records.
  # Groups 95 and 99 both include player #67 (Mal McNeill), so they're combined into a
  # single 3-way merge into Malachy McNeill (#17).
  def up
    ActiveRecord::Base.transaction do
      # Group 1 (Very likely: Same spelling, case difference only)
      # -> Adam Farrell (#1512)  <-  ADAM FARRELL (#1618)
      merge_all([1618], into: 1512)

      # Group 2 (Very likely: Same spelling, case difference only)
      # -> Dianne Laube (#646)  <-  Dianne laube (#706)
      merge_all([706], into: 646)

      # Group 3 (Very likely: Same spelling, case difference only)
      # -> Scott McKay (#466)  <-  Scott Mckay (#1246)
      merge_all([1246], into: 466)

      # Group 4 (Very likely: Nickname / shortened first name)
      # -> Alan Vo (#1485)  <-  Al Vo (#927)
      merge_all([927], into: 1485)

      # Group 5 (Likely: Spelling variant)
      # -> Aidan Stafford (#401)  <-  Aiden Stafford (#388)
      merge_all([388], into: 401)

      # Group 6 (Likely: Spelling variant)
      # -> Ana Christina Sarmento (#1368)  <-  Ana Cristina Sarmento (#1394)
      # switched
      merge_all([1368], into: 1394)

      # Group 7 (Likely: Spelling variants, same surname family)
      # -> Archie Ardkor (#380)  <-  Archie Akdor (#1418), Archy Ardkor (#372), Archy Arkdor (#781)
      merge_all([1418, 372, 781], into: 380)

      # Group 8 (Likely: Spelling variant)
      # -> Anthony Jeffrey (#757)  <-  Anthony Jeffery (#835)
      # switched
      merge_all([757], into: 835)

      # Group 9 (Likely: Same person, multiple format variants)
      # -> Bobbie-Jo Quin (#685)  <-  Bobbie Jo Quin (#620), Bobbie Joe (#952)
      merge_all([620, 952], into: 685)

      # Group 10 (Likely: Spelling variant)
      # -> Brendan D'Aquino (#534)  <-  Brendon D'Aquino (#212)
      # switched
      merge_all([534], into: 212)

      # Group 11 (Likely: Spelling variant)
      # -> Brett Cook (#791)  <-  Brett Cooke (#869)
      merge_all([869], into: 791)

      # Group 12 (Likely: Spelling variant)
      # -> Brodie Conroy (#545)  <-  Brody Conroy (#487)
      # switched
      merge_all([545], into: 487)

      # Group 13 (Likely: Spelling variant)
      # -> Blayde Olsen (#1065)  <-  Blade Olson (#1127)
      merge_all([1127], into: 1065)

      # Group 14 (Likely: Spelling variant)
      # -> Chelle Howorth (#1091)  <-  Chellee Howorth (#1558)
      # switched
      merge_all([1091], into: 1558)

      # Group 15 (Likely: Spelling variant)
      # -> Chris Hazel (#647)  <-  Chris Hazell (#659)
      merge_all([647], into: 659)

      # Group 16 (Likely: Short/full first name)
      # -> Christopher Sourris (#889)  <-  Chris Sourris (#1066)
      merge_all([1066], into: 889)

      # Group 17 (Likely: Short/full first name)
      # -> Christopher Sutton (#656)  <-  Chris Sutton (#939)
      merge_all([939], into: 656)

      # Group 18 (Likely: Spelling variant)
      # -> Daniel Hartup (#375)  <-  Daniel Harup (#745)
      merge_all([745], into: 375)

      # Group 19 (Likely: Spelling variant)
      # -> Darren Wallace (#1101)  <-  Darron Wallace (#946)
      # switched
      merge_all([1101], into: 946)

      # Group 20 (Likely: Short/full first name)
      # -> David Collingridge (#1245)  <-  Dave Collingridge (#1260)
      merge_all([1260], into: 1245)

      # Group 21 (Likely: Short/full first name)
      # -> David Ewing (#70)  <-  Dave Ewing (#444)
      merge_all([444], into: 70)

      # Group 22 (Likely: Short/full first name)
      # -> David Jaensch (#700)  <-  Dave Jaensch (#544)
      merge_all([544], into: 700)

      # Group 23 (Likely: Spelling variant)
      # -> David Limareff (#609)  <-  Dave Limeriff (#1177)
      merge_all([1177], into: 609)

      # Group 24 (Likely: Short/full first name)
      # -> David Mierocha (#1608)  <-  Dave Mierocha (#1540)
      merge_all([1540], into: 1608)

      # Group 25 (Likely: Short/full first name)
      # -> David Rothall (#63)  <-  Dave Rothall (#1228)
      merge_all([1228], into: 63)

      # Group 26 (Likely: Short/full first name)
      # -> David Staver (#94)  <-  Dave Staver (#1585)
      merge_all([1585], into: 94)

      # Group 27 (Likely: Spelling variant)
      # -> Dwayne Anderson (#1147)  <-  DeWayne Anderson (#1015)
      merge_all([1015], into: 1147)

      # Group 28 (Likely: Spelling variant (first+last))
      # -> Donny Frittolli (#799)  <-  Danny Frittoli (#722)
      merge_all([722], into: 799)

      # Group 29 (Likely: Spelling variant)
      # -> Elyce Harris (#683)  <-  Elyse Harris (#1309)
      merge_all([1309], into: 683)

      # Group 30 (Likely: Spelling variants, same surname family)
      # -> George Zamoya (#1406)  <-  George Zomaya (#359), George Z (#1468)
      # switched
      merge_all([1406, 1468], into: 359)

      # Group 31 (Likely: Spelling variant)
      # -> Glenn Croese (#726)  <-  Glen Croese (#886)
      merge_all([886], into: 726)

      # Group 32 (Likely: Spelling variant)
      # -> Hayley Schop (#1550)  <-  Hayley Schopp (#930)
      # switched
      merge_all([1550], into: 930)

      # Group 33 (Likely: Spelling variant)
      # -> Ian Will (#34)  <-  Ian Wills (#810)
      merge_all([810], into: 34)

      # Group 34 (Likely: Spelling variant)
      # -> Jack Schuman (#1056)  <-  Jack Schumann (#978)
      merge_all([978], into: 1056)

      # Group 35 (Likely: Spelling variant)
      # -> Jake Bratzendale (#1219)  <-  Jake Brazendale (#1180)
      # switched
      merge_all([1219], into: 1180)

      # Group 36 (Likely: Spelling variant)
      # -> Jesse Richards (#926)  <-  Jessie Richards (#1016)
      merge_all([1016], into: 926)

      # Group 37 (Likely: Spelling variant)
      # -> Jesse Sumalinog (#629)  <-  Jessie Sumalinog (#696)
      # switched
      merge_all([629], into: 696)

      # Group 38 (Likely: Spelling variant)
      # -> Jim Heijus (#817)  <-  Jim Heinjus (#294)
      merge_all([817], into: 294)

      # Group 39 (Likely: Spelling variant)
      # -> John Durbidge (#569)  <-  John Durbridge (#80)
      merge_all([80], into: 569)

      # Group 40 (Likely: Spelling variant)
      # -> John Pettinato (#905)  <-  John Petinato (#1072)
      merge_all([1072], into: 905)

      # Group 41 (Likely: Short/full name)
      # -> Johnny Zhu (#758)  <-  Johnny Z (#1411)
      merge_all([1411], into: 758)

      # Group 42 (Likely: Short/full name)
      # -> Jon Durand (#1579)  <-  Jonny Durand (#1487)
      merge_all([1487], into: 1579)

      # Group 43 (Likely: Short/full name)
      # -> Joshua Hands (#894)  <-  Josh Hands (#248)
      merge_all([248], into: 894)

      # Group 44 (Likely: Short/full name)
      # -> Joshua Hart (#539)  <-  Josh Hart (#1610)
      merge_all([1610], into: 539)

      # Group 45 (Likely: Short/full name)
      # -> Joshua Hogan (#1535)  <-  Josh Hogan (#1561)
      merge_all([1561], into: 1535)

      # Group 46 (Likely: Spelling variant)
      # -> Kerry Aubrey (#1548)  <-  Kerry Aubery (#1076)
      merge_all([1076], into: 1548)

      # Group 47 (Likely: Spelling variant)
      # -> Lesieli O'Connor (#93)  <-  Leslieli O'Connor (#159)
      merge_all([159], into: 93)

      # Group 48 (Likely: Spelling variant)
      # -> Luke Jowett (#51)  <-  Luke Jowlett (#807)
      merge_all([807], into: 51)

      # Group 49 (Likely: Transposed letters)
      # -> Mark Suhr (#237)  <-  Mark Surh (#98)
      merge_all([98], into: 237)

      # Group 50 (Likely: Short/full/spelling variants)
      # -> Matthew Palko (#83)  <-  Matt Palko (#310), Mathew Palko (#832)
      merge_all([310, 832], into: 83)

      # Group 51 (Likely: Short/full name)
      # -> Matthew Fahey (#1616)  <-  Matt Fahey (#1124)
      merge_all([1124], into: 1616)

      # Group 52 (Likely: Short/full name)
      # -> Matthew Goodlock (#138)  <-  Matt Goodlock (#26)
      merge_all([26], into: 138)

      # Group 53 (Likely: Short/full name)
      # -> Michael Boes (#666)  <-  Mick Boes (#649)
      merge_all([649], into: 666)

      # Group 54 (Likely: Short/full name)
      # -> Michael Girvan (#171)  <-  Mick Girvan (#253)
      merge_all([253], into: 171)

      # Group 55 (Likely: Spelling variant)
      # -> Mick Gray (#281)  <-  Mick Grey (#1081)
      merge_all([1081], into: 281)

      # Group 56 (Likely: Short/full name)
      # -> Michael Reardon (#353)  <-  Mick Reardon (#846)
      merge_all([846], into: 353)

      # Group 57 (Likely: Short/full name)
      # -> Michael Schilling (#732)  <-  Mick Schilling (#795)
      merge_all([795], into: 732)

      # Group 58 (Likely: Short/full name)
      # -> Nicholas Edlinger (#136)  <-  Nic Edlinger (#227)
      merge_all([227], into: 136)

      # Group 59 (Likely: Short/full name)
      # -> Nicholas Serpell (#870)  <-  Nic Serpell (#1352)
      merge_all([1352], into: 870)

      # Group 60 (Likely: Spelling variant)
      # -> Noel Fontana (#806)  <-  Nole Fontana (#729)
      merge_all([729], into: 806)

      # Group 61 (Likely: Spelling variant)
      # -> Padricis Gautam (#286)  <-  Padricis Gautum (#86)
      merge_all([86], into: 286)

      # Group 62 (Likely: Spelling variant / typo)
      # -> Rhys Godden (#11)  <-  Rhys Goddem (#528)
      merge_all([528], into: 11)

      # Group 63 (Likely: Spelling variant)
      # -> Robert Hickfuss (#993)  <-  Rob Hinckfuss (#1018)
      # switched
      merge_all([993], into: 1018)

      # Group 64 (Likely: Spelling variant)
      # -> Robert Lo Rosso (#828)  <-  Robby Lorosso (#718)
      merge_all([718], into: 828)

      # Group 65 (Likely: Spelling variant)
      # -> Ron Callander (#1185)  <-  Ron Callender (#882)
      merge_all([1185], into: 882)

      # Group 66 (Likely: Spelling variant)
      # -> Scott Frankcombe (#411)  <-  Scott Francombe (#424)
      merge_all([424], into: 411)

      # Group 67 (Likely: Short/full name)
      # -> Sebastyan Thompson (#1019)  <-  Seb Thompson (#949)
      merge_all([949], into: 1019)

      # Group 68 (Likely: Transposed letters)
      # -> Stan Iakovakis (#364)  <-  Stan Lakovakis (#276)
      merge_all([276], into: 364)

      # Group 69 (Likely: Spelling variant)
      # -> Steve Brosnahan (#731)  <-  Steve Brosnan (#1169)
      merge_all([1169], into: 731)

      # Group 70 (Likely: Short/full name)
      # -> Samuel Southwell (#896)  <-  Sam Southwell (#1505)
      merge_all([1505], into: 896)

      # Group 71 (Likely: Short/full name)
      # -> Samuel Burnett (#1609)  <-  Sam Burnett (#1494)
      merge_all([1494], into: 1609)

      # Group 72 (Likely: First/last order swapped)
      # -> Vasu Chauhan (#303)  <-  Chauhan Vasu (#243)
      # switched
      merge_all([303], into: 243)

      # Group 73 (Likely: Same person, 3 name-format variants)
      # -> Thomas D'Arcy (#1102)  <-  Thomas Darcy (#971), Tom Darcy (#1061)
      # switched
      merge_all([1102, 1061], into: 971)

      # Group 74 (Likely: Spelling variant)
      # -> Mike Ballam (#180)  <-  Mike Ballan (#92)
      merge_all([92], into: 180)

      # Group 75 (Likely: Short/full name)
      # -> Rick Bariola (#752)  <-  Ricky Bariola (#822)
      merge_all([822], into: 752)

      # Group 76 (Likely: Spelling variant / possible data entry error)
      # -> Robert Dennis (#617)  <-  bobby Dennis (#699)
      merge_all([699], into: 617)

      # Group 77 (Likely: Short/full name)
      # -> William Keogh (#84)  <-  Will Keogh (#188)
      merge_all([188], into: 84)

      # Group 78 (Likely: Short/full name)
      # -> Timothy Olsen (#1514)  <-  Tim Olsen (#899)
      merge_all([899], into: 1514)

      # Group 79 (Likely: Short/full name)
      # -> Thomas O'Keefe (#615)  <-  Tom O'Keefe (#379)
      merge_all([379], into: 615)

      # Group 80 (Likely: Short/full name)
      # -> Susan McCord (#1089)  <-  Sue McCord (#925)
      merge_all([925], into: 1089)

      # Group 81 (Likely: Spelling variant)
      # -> Shane McCulloch (#239)  <-  Shayne McCulloch (#421)
      merge_all([239], into: 421)

      # Group 82 (Likely: Spelling variant)
      # -> Brendan Smith (#844)  <-  Brendon Smith (#69)
      merge_all([69], into: 844)

      # Group 83 (Likely: Short/full name)
      # -> Len Stein (#910)  <-  Lenny Stein (#1079)
      merge_all([1079], into: 910)

      # Group 84 (Likely: Spelling variant)
      # -> Steven Tzafaris (#334)  <-  Steve Tzafaris (#258)
      merge_all([258], into: 334)

      # Group 85 (Likely: Spelling variant)
      # -> Vijay Randall (#342)  <-  Vjay Randall (#1119)
      merge_all([1119], into: 342)

      # Group 86 (Likely: Shortened / truncated entry)
      # -> Jack Couchman (#147)  <-  Jack Cou (#1192)
      merge_all([1192], into: 147)

      # Group 87 (Likely: Spelling variant)
      # -> Tanarv Mahadea (#119)  <-  Tan Mahadea (#234)
      merge_all([234], into: 119)

      # Group 88 (Likely: Spelling variant)
      # -> Tolovae Auva'a (#77)  <-  Tolly Auva'a (#153)
      merge_all([153], into: 77)

      # Group 89 (Likely: Same person, extra tag on one entry)
      # -> Joel Slatter (#1156)  <-  Joel Slatter TW (#940)
      merge_all([940], into: 1156)

      # Group 90 (Likely: Short/full name)
      # -> Phillip Lee (#754)  <-  Phil Lee (#838)
      merge_all([838], into: 754)

      # Group 91 (Worth a look: Nickname could be same person)
      # -> Ace O'Keefe (#357)  <-  Ace O (#1397)
      merge_all([1397], into: 357)

      # Group 92 (Worth a look: Spelling variants of same name)
      # -> Bradley Joyes (#1386)  <-  Brad Joyce (#44), Brad Joyes (#103)
      merge_all([44, 103], into: 1386)

      # Group 93 (Worth a look: Short/full name)
      # -> Bradley Oakman (#293)  <-  Brad Oakman (#877)
      merge_all([877], into: 293)

      # Group 94 (Worth a look: Short/full name, could be different people)
      # -> Christian Furner (#1544)  <-  Chris Furner (#999)
      merge_all([999], into: 1544)

      # Group 95+99 (Worth a look: id 67 (Mal McNeill) appears in both groups; merging all three into Malachy McNeill)
      # -> Malachy McNeill (#17)  <-  Mal McNeill (#67), Mel Mcneil (#818)
      merge_all([67, 818], into: 17)

      # Group 97 (Worth a look: Common name, may be two different people)
      # -> Graeme Wright (#792)  <-  Graham Wright (#854)
      merge_all([854], into: 792)

      # Group 98 (Worth a look: Short/full name)
      # -> Frank Walker (#1334)  <-  Frankie Walker (#1302)
      merge_all([1302], into: 1334)
    end
  end

  def down
    raise ActiveRecord::IrreversibleMigration
  end

  private

  def merge_all(other_ids, into:)
    survivor = Player.find(into)
    other_ids.each do |id|
      Player.find(id).merge_into(survivor)
    end
  end
end
